docs(#1383): short fixes in documentation
spaship/spaship pull request #1500
Opened 2021-12-07 15:38 UTC by shruticode81

## Closes / Fixes / Resolves

## Explain the feature/fix

Added short fixes for documentation package

## Does this PR introduce a breaking change

No

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [X] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2021-12-08 12:10 UTC, arkaprovob approved these changes

2021-12-14 16:30 UTC, sayak-sarkar requested changes

2021-12-14 16:30 UTC, sayak-sarkar commented on packages/documentation/docs/qa-testing/test-process.md
> +* To have a process documentation of manual testing
```suggestion
* To have an automation testing framework setup for testing the SPAship Manager and SPAship Operator functionalities
* To have a process documentation of manual testing
```

2021-12-21 10:21 UTC, sayak-sarkar approved these changes

2021-12-21 10:21 UTC, merged