Github action update for SPAship manager
spaship/spaship pull request #1873
Opened 2022-09-20 15:14 UTC by arkaprovob

## Resolves

GitHub action for the manager is updated as per build requirements.

## Explain the feature/fix

Only change in manager-build action

## Does this PR introduce a breaking change

No

## Screenshot(s)
![Screenshot from 2022-09-20 20-39-40](https://user-images.githubusercontent.com/47105136/191296429-b0fe5ebf-e39f-4921-a608-ebcb88f60fe0.png)
![Screenshot from 2022-09-20 20-39-35](https://user-images.githubusercontent.com/47105136/191296464-202dcd06-82de-43f9-9698-556071b4f016.png)

2022-09-20 15:16 UTC, akhilmhdh approved these changes

2022-09-20 17:10 UTC, soumyadip007 approved these changes

2022-09-20 17:19 UTC, riginoommen requested changes

2022-09-20 17:19 UTC, riginoommen commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
```suggestion
```

2022-09-20 17:19 UTC, riginoommen commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
```suggestion
```

2022-09-20 17:19 UTC, riginoommen commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
```suggestion
```

2022-09-20 17:19 UTC, riginoommen commented on .github/workflows/manager-ci.yaml
>            #file: ./packages/manager/Dockerfile
```suggestion
```

2022-09-20 17:19 UTC, riginoommen commented on .github/workflows/manager-ci.yaml
>            #file: ./packages/manager/Dockerfile
```suggestion
```

2022-09-21 00:26 UTC, arkaprovob commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
removed

2022-09-21 00:26 UTC, arkaprovob commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
remoevd

2022-09-21 00:26 UTC, arkaprovob commented on .github/workflows/manager-ci.yaml
> +          #file: ./packages/manager/Dockerfile
removed

2022-09-21 00:26 UTC, arkaprovob commented on .github/workflows/manager-ci.yaml
>            #file: ./packages/manager/Dockerfile
removed

2022-09-21 00:26 UTC, arkaprovob commented on .github/workflows/manager-ci.yaml
>            #file: ./packages/manager/Dockerfile
removed

2022-09-21 05:08 UTC, riginoommen approved these changes

2022-09-21 05:08 UTC, merged