feat(api) : event stream producer added
spaship/spaship pull request #1980
Opened 2022-11-09 15:57 UTC by soumyadip007

Subject:  feat(api) : event stream producer added 
Assignees: @soumyadip007 

## Closes / Fixes / Resolves

1. Deployment connection and analytics typo fixed
2. SSE producer implemented 
3. Events added into API
4. SSE added for all the activities 
5. /analytics/events end point added for SSE
6. Realtime Activity Stream Creation, Deletion of Env, Property, APIKey, Deploment of Applications

## Does this PR introduce a breaking change

NO

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2022-11-09 16:06 UTC, hybridx requested changes

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/app.module.ts
> +import { DeploymentConnectionModule } from './server/deployment-conncection/service/deployment-connection.module';
```suggestion
import { DeploymentConnectionController } from './server/deployment-conncection/deployment-connection.controller';
import { DeploymentConnectionModule } from './server/deployment-conncection/service/deployment-connection.module';
```

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/repository/data-services.abstract.ts
> +import { DeploymentConnection } from '../server/deployment-conncection/deployment-connection.entity';
```suggestion
import { DeploymentConnection } from '../server/deployment-conncection/deployment-connection.entity';
```

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/server/analytics/service/analytics.service.ts
> +}
```suggestion
}

```

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/server/application/service/application.service.ts
> +      this.logger.log('Agenda', JSON.stringify(agendaResponse));
Do we need the entire response?
We can add this response into different levels right?

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/server/deployment-conncection/service/deployment-connection.factory.ts
> +import { DeploymentConnectionDTO, UpdateDeploymentConnectionDTO } from 'src/server/deployment-conncection/deployment-connection.dto';
```suggestion
import { DeploymentConnectionDTO, UpdateDeploymentConnectionDTO } from 'src/server/deployment-conncection/deployment-connection.dto';
```

2022-11-09 16:06 UTC, hybridx commented on packages/api/src/server/deployment-conncection/service/deployment-connection.service.ts
> +import { DeploymentConnectionDTO, UpdateDeploymentConnectionDTO } from 'src/server/deployment-conncection/deployment-connection.dto';
```suggestion
import { DeploymentConnectionDTO, UpdateDeploymentConnectionDTO } from 'src/server/deployment-connection/deployment-connection.dto';
```

2022-11-09 16:53 UTC, soumyadip007 commented on packages/api/src/server/deployment-conncection/service/deployment-connection.service.ts
> +import { DeploymentConnectionDTO, UpdateDeploymentConnectionDTO } from 'src/server/deployment-conncection/deployment-connection.dto';
Resolved

2022-11-09 16:53 UTC, soumyadip007 commented on packages/api/src/repository/data-services.abstract.ts
> +import { DeploymentConnection } from '../server/deployment-conncection/deployment-connection.entity';
Resolved

2022-11-09 19:12 UTC, soumyadip007 commented on packages/api/src/server/analytics/service/analytics.service.ts
> +}
Resolved

2022-11-09 19:12 UTC, soumyadip007 commented
@hybridx  I've resolved your comments and added the documentation for the services. Please check.

2022-11-10 05:20 UTC, hybridx approved these changes

2022-11-10 05:20 UTC, merged