fix(manager): Table skeleton loading on filter value change and page refresh
spaship/spaship pull request #2119
Opened 2023-01-20 12:04 UTC by nikhitamore

## Closes / Fixes / Resolves

## Explain the feature/fix
Table skeleton is loading on page refresh, new filter value.

## Does this PR introduce a breaking change

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/26894183/213690770-92e06cf4-3470-4082-b093-3e8989c26963.png">

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/26894183/213690856-408153fe-4478-48ff-b4e3-f5e33f609366.png">

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2023-01-20 15:30 UTC, soumyadip007 approved these changes

2023-01-23 04:17 UTC, akhilmhdh requested changes

2023-01-23 04:17 UTC, akhilmhdh commented on packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
> +                            )} */}
Why though 🤔

2023-01-23 04:17 UTC, akhilmhdh commented on packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
> +                  {(spaProperties.isLoading && webProperties.isLoading) ||
How about we join this together

2023-01-23 08:19 UTC, nikhitamore commented on packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
> +                  {(spaProperties.isLoading && webProperties.isLoading) ||
done

2023-01-23 08:54 UTC, akhilmhdh approved these changes

2023-01-24 06:01 UTC, hybridx approved these changes

2023-01-24 06:02 UTC, merged