feat(manager): Workflow 3.0
spaship/spaship pull request #2305
Opened 2023-04-21 13:10 UTC by nikhitamore

## Closes / Fixes / Resolves

## Explain the feature/fix

## Does this PR introduce a breaking change

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2023-05-07 15:41 UTC, riginoommen requested changes

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/Notification.tsx
> +// };
Why the code is commented

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/Notification.tsx
> +const data1 = {
```suggestion
const data = {
```

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/Notification.tsx
> +        '{"accessUrl":"https://testnikki-dev.apps.int.mpp.preprod.iad2.dc.paas.redhat.com/"}',
Don't expose this urls

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/Notification.tsx
> +        '{"accessUrl":"https://testnikki-dev.apps.int.mpp.preprod.iad2.dc.paas.redhat.com/"}',
Same here

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/Notification.tsx
> +// const currentStepObj = steps.find((step) => step.step === state.step);
```suggestion
// useEffect(() => {
//   let currentStep = state.step;
//   const interval = setInterval(() => {
//     currentStep++;
//     if (currentStep > 5) {
//       clearInterval(interval);
//     } else {
//       setState({
//         ...state,
//         step: currentStep
//       });
//       console.log(state.step);
//     }
//   }, 3000);
//   return () => clearInterval(interval);
// }, []);

// const currentStepObj = steps.find((step) => step.step === state.step);
```

Why this code is commented

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx
> +                    isActive={pathname === pageLinks.webPropertyListPage}
```suggestion
                    isActive={pathName === pageLinks.webPropertyListPage}
```

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
> +          propertyIdentifier={propertyIdentifier}
Why here also commented code

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/views/WebPropertyDetailPage/components/DeploymentProgress/DeploymentProgress.tsx
> +  // {
Please remove this commented code

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/views/WebPropertyDetailPage/components/DeploymentProgress/DeploymentProgress.tsx
> +    // newData[currentStep] = ProgressVariant.success;
```suggestion

```

2023-05-07 15:41 UTC, riginoommen commented on packages/manager/src/views/WebPropertyDetailPage/components/addDeployment.tsx
> +// import { Switch, Tooltip } from '@patternfly/react-core';
Why this code block is commented

2023-05-09 13:50 UTC, closed without merging

2023-05-09 13:50 UTC, nikhitamore commented
Changing branch