feat(spaship) : orchestrator and manager patches for 23.05.0 release
spaship/spaship pull request #2366
Opened 2023-06-05 05:38 UTC by soumyadip007

Subject:  feat(spaship) : orchestrator and manager patches for 23.05.0 release

## Closes / Fixes 

1. All the changes are already reviewed for the 23.05.0 branch, as we've done the release we're moving the patches to the master branch 
2. Changes in Orchestrator
3. Changes in Manager

## Pull requests (Reviewed)

- chore(api) : get dockerfile port without apllication check (#2358)
- fix(manager) : separating port and app validations (#2359)
- chore(api) : changes into config variable for namespace (#2361)
- fix(manager) : removing toast message from sidebar (#2360)
- feat(manager): validation call fix on stage one
- fix(Manager) : error message not going (#2363)
- fix(manager) : removing application error after correct input (#2364)

## Does this PR introduce a breaking change

NO

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2023-06-05 07:49 UTC, nikhitamore approved these changes
good

2023-06-05 11:09 UTC, hybridx requested changes

2023-06-05 11:09 UTC, hybridx commented on packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx
> +        if (Object.keys(response).includes('port')) {
have you tried `responses.hasOwnProperty`

2023-06-06 07:44 UTC, hybridx approved these changes

2023-06-06 09:50 UTC, merged