Feat(Manager) Environment filter in spa detailed page
spaship/spaship pull request #2498
Opened 2023-10-25 09:51 UTC by pjain24

## Closes / Fixes / Resolves

Closes #issue_id

## Explain the feature/fix

I have implemented an "Environment Filter" on the SPA Detailed Page, which allows stakeholders to filter and view all SPAs within a specific environment. This feature provides a convenient way for stakeholders to search and access relevant information, enhancing the user experience.

## Does this PR introduce a breaking change

No

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

![Screenshot from 2023-10-25 15-04-53](https://github.com/spaship/spaship/assets/39623025/206e7953-96b3-410e-8a16-9aa24f5fc36e)

![Screenshot from 2023-10-25 15-05-07](https://github.com/spaship/spaship/assets/39623025/25bcc541-08c3-4755-a1d9-58af17a38437)
![Screenshot from 2023-10-25 15-05-15](https://github.com/spaship/spaship/assets/39623025/1ba1add5-e3fc-4722-bfc7-d06c7b62dd47)

</details>

2023-12-04 06:58 UTC, soumyadip007 commented on packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx
> +            // style={{ width: '300px!important' }}
Please remove the comment

2023-12-06 05:49 UTC, nikhitamore requested changes

2023-12-06 05:49 UTC, nikhitamore commented on packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
> +          <Select
@pjain24 Can you try writing a separate component EnvFilter for this , and call it in containerized and static, as code is being repeated in both the files.
Create a component that accepts data and returns a dropdown

2023-12-06 05:49 UTC, nikhitamore commented on packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
> +                        key={val.env}
May I ask why was this key changed, {`autoSync-${val.name}`} to env

2023-12-06 05:52 UTC, nikhitamore commented on packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
> +  symlink: [];
Why was TSymlink removed

2023-12-06 05:54 UTC, soumyadip007 commented
Hi @pjain24 , I can see a lot of API changes and Manager Overridden code in the PR. Please rebase it.

2023-12-06 05:56 UTC, soumyadip007 commented on packages/api/src/repository/mongo/model/environment.model.ts
>    @Prop({ default: 'NA' })
This is API change, and already released, please rebase it.

2023-12-06 05:56 UTC, soumyadip007 commented on packages/api/package.json
> -  "version": "4.0.0",
This is API change, and already released, please rebase it.

2023-12-06 05:56 UTC, soumyadip007 commented on packages/api/src/server/analytics/activity-stream.entity.ts
>    WEBHOOK_UPDATED = 'WEBHOOK_UPDATED',
This is an API change, and already released, please rebase it.

2023-12-06 05:56 UTC, soumyadip007 commented on packages/api/src/server/application/service/application.service.ts
>        applicationDetails.nextRef = this.applicationFactory.getNextRef(applicationRequest.ref) || 'NA';
This is API change, and already been released, please rebase it.

2023-12-20 07:52 UTC, nikhitamore commented
Closing as created 2520 with proper rebasing and code

2023-12-20 07:52 UTC, closed without merging