chore(deps): fix dependencies conflicts
spaship/spaship pull request #872
Opened 2020-10-28 06:47 UTC by kunyan

Since the `react-scripts` has been upgraded to v4
There are some conflicts like `eslint`, `jest` with the root package.json

## Closes / Fixes / Resolves

## Explain the feature/fix

## Does this PR introduce a breaking change

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2020-10-28 06:50 UTC, kunyan commented
@mwcz  @sayak-sarkar 

I still suggest we should move `manager` and `documentation` out of monorepo

for `manager`, it is using `react-scripts`, which included many dependencies and will conflict with our root package.json setting. now, we can not easily upgrade the `react-scripts` or the `eslint`, `jest` in root package.json

for documentation. it's not created by us. we only create markdown files. so we should not put it into the `packages`
it also has some dependencies issue

2020-10-28 06:51 UTC, kunyan commented
Both of them has nothing to share with other packages.

2020-10-28 08:19 UTC, sayak-sarkar requested changes

2020-10-28 08:19 UTC, sayak-sarkar commented on packages/documentation/package.json
> +    "@docusaurus/preset-classic": "2.0.0-alpha.66",
There are some issues with this version of Docusaurus which is why @mwcz rolled back this version in his last PR.

2020-10-28 08:21 UTC, sayak-sarkar commented
Instead of breaking up the monorepo, we can simply configure lerna and renovate to maintain separate dependency versions for individual packages. That way dependency updates to one package wont impact the other one.

2020-11-06 18:51 UTC, mwcz commented
I agree with @sayak-sarkar, we shouldn't break up the monorepo.  I've said a million times that the ability to clone the project, `npm install`, and `npm start` to get a working environment is critical.  I'm going to keep saying it until we get there.  Keeping the monorepo together is essential.

If we pull manager and docs out of the monorepo, here's what will happen:

 - documentation will be updated out of sync with the actual features landing, if it gets updated at all
 - changes to the API will not be well tested with manager
 - onboarding new contributors will be more difficult, requiring more documentation, and more fielding of questions
 - version numbers of manager and the rest of SPAship will be out of sync

Solution:

If some devDependencies in the monorepo differ from what's in some packages, move the conflicting root packages into the _other_ packages' dep tree.  Ie, remove eslint from root/package.json and put it into the package.json's for every package that needs that version.  Renovate will take care of keeping the versions up to date, so there's no extra burden on us.

2020-11-17 12:06 UTC, closed without merging