feat(router): add forwarded_host options to support router behind a proxy
spaship/spaship pull request #916
Opened 2020-11-12 08:25 UTC by kunyan

## Closes / Fixes / Resolves

## Explain the feature/fix

## Does this PR introduce a breaking change

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

2020-11-17 12:07 UTC, sayak-sarkar requested changes

2020-11-17 12:11 UTC, sayak-sarkar requested changes

2020-11-17 12:11 UTC, sayak-sarkar commented on packages/router/index.js
> +   * If we fount forwared_host in config, will use it as host
```suggestion
   * If forwarded_host is found in config, use it as host
```

2020-11-17 12:11 UTC, sayak-sarkar commented on packages/router/index.js
> +   * If x-forwared-host has some different value. will use it as host
```suggestion
   * If x-forwarded-host has some different value, use it as host
```

2020-11-17 12:12 UTC, sayak-sarkar commented
Hey @Jared-Sprague Can you please review this PR?

2020-12-09 05:46 UTC, sayak-sarkar commented
Hey @Jared-Sprague Can you please review this PR as soon as possible? It's been in the pending review state for a month now.

2020-12-16 14:15 UTC, Jared-Sprague approved these changes
Looks good to me! Thanks @kunyan !!

2020-12-16 14:32 UTC, sayak-sarkar approved these changes

2020-12-16 14:36 UTC, merged